# Generated by Django 5.1.7 on 2025-03-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='products',
            field=models.ManyToManyField(to='task.product'),
        ),
    ]
