# Generated by Django 5.1.7 on 2025-03-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_person_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='products',
        ),
    ]
